In [1]:
import numpy as np

In [2]:
li =[5,4,3,2,1]
li2=[10,9,8,7,6]

In [4]:
arry1=np.array(li) 

In [9]:
np.ones([5,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
np.zeros([5,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [22]:
np.arange(0,33,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [42]:
np.empty(2)

array([5.43230922e-312, 7.29112202e-304])

In [36]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])